server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true

spring:
  profiles:
    include:
      - oauth

  h2:
    console:
      enabled: true
      path: /h2-console

#  devtools:
#    livereload:
#      enabled: true
#    restart:
#      enabled: true
#  mustache:
#    cache: false

  datasource:
#    database:
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://localhost:3307/photogram2?serverTimezone=Asia/Seoul
#    username: cos
#    password: cos1234

    h2:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:testdb

  jpa:
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB

  security:
    user:
      name: test
      password: 1234

file:
  path:
    image:  C:/upload/photogram/image/
    profile: C:/upload/photogram/profile/
